"""Shared repository contract used by API services."""

from __future__ import annotations

from typing import Any, Mapping, Protocol, Sequence

import pandas as pd


class DataRepository(Protocol):
    """Minimum data-access surface required by forecasting and tools."""

    def load_modeling_data(self) -> pd.DataFrame: ...

    def load_daily_sales(self) -> pd.DataFrame: ...

    def list_products(self) -> list[str]: ...

    def product_exists(self, product_name: str) -> bool: ...

    def get_product_history(self, product_name: str) -> pd.DataFrame: ...

    def get_latest_business_state(self) -> pd.DataFrame: ...

    def get_latest_prices(self) -> pd.Series: ...

    def get_last_historical_date(self) -> pd.Timestamp: ...

    def save_recommendations(self, payload: Mapping[str, Any]) -> None: ...

    def get_latest_recommendations(
        self, horizon_days: int | None = None
    ) -> Mapping[str, Any] | None: ...

    def insert_sales(self, records: Sequence[Mapping[str, Any]]) -> Mapping[str, Any]: ...
