"""Assistant request and response schemas."""

from typing import Annotated, Literal

from pydantic import BaseModel, Field, StringConstraints

AssistantMessage = Annotated[
    str,
    StringConstraints(
        strip_whitespace=True,
        min_length=1,
        max_length=2000,
    ),
]


class AssistantRequest(BaseModel):
    """Request body for a message sent to the AI assistant."""

    message: AssistantMessage = Field(
        ...,
        description="User message sent to the MotoStock AI assistant",
        examples=[
            "What is the purpose of MotoStock AI?",
        ],
    )


class AssistantSource(BaseModel):
    """Stable provenance metadata returned for retrieved knowledge."""

    source: str = Field(..., min_length=1)
    section: str = Field(..., min_length=1)
    chunk_id: str = Field(..., min_length=1)
    score: float = Field(..., ge=-1.0, le=1.0)


class AssistantResponse(BaseModel):
    """Response returned by the MotoStock AI assistant."""

    answer: str = Field(
        ...,
        min_length=1,
        description="Final answer generated by the AI assistant",
        examples=[
            (
                "MotoStock AI forecasts product demand and supports "
                "stock replenishment decisions."
            )
        ],
    )

    model: str = Field(
        ...,
        min_length=1,
        description="Language model used to generate the answer",
        examples=["qwen3:4b"],
    )

    tools_used: list[str] = Field(
        default_factory=list,
        description="Names of the tools used to generate the answer",
    )

    sources: list[AssistantSource] = Field(
        default_factory=list,
        description="Document chunks used to support the answer",
    )


class AssistantErrorResponse(BaseModel):
    """Standard error response for assistant endpoints."""

    detail: str = Field(
        ...,
        description="Human-readable error message",
        examples=["Ollama service is unavailable."],
    )


class AssistantHealthResponse(BaseModel):
    """Health status of the AI assistant dependencies."""

    status: Literal[
        "ok",
        "ollama_unavailable",
        "model_unavailable",
    ] = Field(
        ...,
        description="Current availability status of the AI assistant",
    )

    ollama_available: bool = Field(
        ...,
        description="Whether the Ollama server is available",
    )

    model: str = Field(
        ...,
        min_length=1,
        description="Configured language model",
        examples=["qwen3:4b"],
    )

    model_available: bool = Field(
        ...,
        description="Whether the configured model is installed in Ollama",
    )
